### PR TITLE
multiprotocol server support

### PR DESCRIPTION
**Pull request by jkent**
This is a desired feature for GrangerHub's S00N(TM) to be released multiprotocol Tremulous server -- currently hosting test7341, GrangerPub, and GrangerClub servers -- the reason for this change is so that only one port needs to be opened to be listed for protocols 69, 70, and 71.  An advantage to this is that a player's GUID will be the same no matter how they connect to the server.

The current master server deployment would also need to change: instead of two instances we would need a single instance -- I guess that could be done with an iptables rule or the master server could be modified to listen to multiple ports.

### CODE REVIEW

**Comment by timangus** [comment]
I'm not sure this makes a lot of sense without also having the server listen on multiple ports... unless I'm missing something?

**Comment by jkent** [comment]
@timangus: by server, I'm guessing you mean master?  I will go ahead and modify it to listen on multiple ports (eg, 30700 and 30710).  I was thinking something like

```
iptables -t nat -A PREROUTING -i eth0 -p udp --dport 30700 -j REDIRECT --to-ports 30710
```

to achieve the same result.

**Comment by timangus** [comment]
Yeah sorry, the master server is what I meant. Firewall redirects would of course work, but seems like a hack to fix what should exist in the master server itself... IMHO.

**Comment by timangus** [comment]
Also, should probably do it here https://github.com/darklegion/tremulous-master, as I doubt Ben cares much :).

**Comment by jkent** [comment]
Very good.  Thanks.

**Pull request closed without merging**
